# ci_build.yml
name: 'Build and push Artifact'
description: 'Building and Pushing Artifact to Azure Artifact Repository'
inputs:
  pom_path:
    required: false
  pom_file_name:
    required: false
  build_tool:
    required: false
  settings_file_path:
    required: false
  cr_servername:
    required: true
  az_artifact_repository_pat:
    required: true
  
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
    
runs:
  using: "composite"
  steps:
    - run: echo Hello, You are Executing Composite action to Execute Build
      shell: bash
    - run: ls -lart
      shell: bash
    
    - name: Maven Build and Publish to Azure Artifacts
      run: |
        mvn clean install
      shell: bash  
    
    - name: Unit_Test
      run : | 
        echo Running Unit Test 
        mvn test 
      shell: bash
    
    - name: Deploy Artifact
      run : |
        echo 'Testing - completed'
        deploy -s settings.xml -Dazrepo.pat=${{ inputs.az_artifact_repository_pat }}
      shell: bash 
