# ci_build.yml
name: 'Build and push Artifact'
description: 'Building and Pushing Artifact to Azure Artifact Repository'
inputs:
  pom_path:
    required: false
    default: .
  pom_file_name:
    required: false
    default: pom.xml
  build_tool:
    required: false
    default: mvn
  settings_file_path:
    required: false
    default: .
  settings_file_name:
    required: false
    default: settings.xml
  az_artifact_repository_pat:
    required: false
  
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
    
runs:
  using: "composite"
  steps:
    - run: echo Hello, You are Executing Composite action to Execute Build
      shell: bash
    - run: ls -lart
      shell: bash
    
    - name: Maven Build and Publish to Azure Artifacts
      run: |
        mvn clean install -f ./${{ inputs.pom_path }}/${{ inputs.pom_file_name }}
      shell: bash  
    
    - name: Unit_Test
      run : | 
        echo Running Unit Test 
        mvn test -f ./${{ inputs.pom_path }}/${{ inputs.pom_file_name }}
      shell: bash
    
    - name: Deploy Artifact
      run : |
        echo 'Testing - completed'
        mvn deploy -s ./${{ inputs.settings_file_path }}/${{ inputs.settings_file_name }} -Dazrepo.pat=${{ inputs.az_artifact_repository_pat }} -f ./${{ inputs.pom_path }}/${{ inputs.pom_file_name }}
      shell: bash 
