# Appsec Composite action
name: 'DevSecOps Application Security Actions'
description: 'Running Security Scans for project codes'
inputs:
  snyk_token:
    required: true
  prisma_user:
    required: false
  prisma_password:
    required: false
  docker_image_name:
    required: false
  docker_image_tag:
    required: false
    
runs:
  using: "composite"
  steps:
    - run: echo Hello, You are Executing Composite action to Execute Build
      shell: bash
    - run: ls -lart
      shell: bash
      
    - name: Snyk SCA Scanning
      continue-on-error: true
      run: |
        echo "----------Download Latest Snyk CLI-----------"
        curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.683.0/snyk-linux"
        chmod +x snyk
        ls -lrt
        ./snyk auth ${{inputs.Snyk_token}}
        ./snyk test --all-projects
        ./snyk monitor --all-projects
        
     - name: Run Prisma Cloud Scan
       run: |
         curl --user ${{ inputs.prisma_user }}:${{ inputs.prisma_password }} --output ./twistcli ${{ secrets.PRISMA_URL }}/api/v1/util/twistcli
         chmod a+x ./twistcli     
    
     - name: Scan the image using Prisma Cloud 
       run: ./twistcli images scan --address ${{ secrets.PRISMA_URL }} --user ${{ inputs.prisma_user }} --password ${{ inputs.prisma_password }} --details ${{inputs.docker_image_name}}:${{inputs.docker_image_tag}}
    
